version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
    target-branch: 'main'
    open-pull-requests-limit: 10
    labels: ['dependencies']
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps(dev)'
    groups:
      eslint-and-friends:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - '@testing-library/*'
          - 'playwright'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5
    labels: ['dependencies', 'ci']
