name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1.55.0

      - name: Install Playwright (Chromium)
        run: pnpm exec playwright install --with-deps chromium

      - name: Cache Vite/Esbuild caches
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules/.vite
            **/node_modules/.cache/esbuild
          key: ${{ runner.os }}-vite-${{ hashFiles('pnpm-lock.yaml', 'vite.config.ts', 'tsconfig*.json') }}

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test -- --coverage

      - name: Build
        run: pnpm build

      - name: Build Storybook
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: pnpm build-storybook
