name: Commitlint

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

concurrency:
  group: commitlint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
          token: ${{ secrets.GITHUB_TOKEN }}
